# Generated by Django 4.2.6 on 2023-11-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_records_andrede_name_alter_records_land_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='stadt',
            name='stadt_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
