# Generated by Django 4.2.6 on 2023-11-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_land_land_name_alter_stadt_stadt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='andrede_name',
        ),
        migrations.RemoveField(
            model_name='records',
            name='land_name',
        ),
        migrations.RemoveField(
            model_name='records',
            name='stadt_name',
        ),
    ]
