# Generated by Django 4.2.6 on 2023-11-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_remove_records_andrede_name_remove_records_land_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andrede',
            name='timestamp',
        ),
    ]
