# Generated by Django 4.2.6 on 2023-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_andrede_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andrede',
            name='andrede_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
