# Generated by Django 4.2.6 on 2023-11-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_andrede_andrede_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Andrede',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.DeleteModel(
            name='Stadt',
        ),
    ]
