# Generated by Django 4.2.6 on 2023-11-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0007_delete_andrede_delete_land_delete_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andrede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('andrede_name', models.CharField(blank=True, default=None, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('land_name', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=155, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=155, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=155, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('news_accept', models.BooleanField(default=False)),
                ('telefone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('starBe', models.TextField(blank=True, default=None, null=True)),
                ('nr', models.CharField(blank=True, default=None, max_length=155)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('uid_number', models.CharField(blank=True, max_length=55, null=True)),
                ('ammerkung', models.TextField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stadt_name', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
    ]
