# Generated by Django 4.2.6 on 2023-11-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='andrede_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_andrede_name', to='maintenance.andrede'),
        ),
        migrations.AddField(
            model_name='records',
            name='land_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_land_name', to='maintenance.land'),
        ),
        migrations.AddField(
            model_name='records',
            name='stadt_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_stadt_name', to='maintenance.stadt'),
        ),
    ]
