# Generated by Django 4.2.6 on 2023-11-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_records_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='andrede_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_andrede_name', to='maintenance.andrede'),
        ),
    ]
